### ISSUE TITLE
Missing code perhaps?

### ISSUE THREAD

**Issue by zsiddiqi** [antkaynak/Keyist-Ecommerce#1]
Hi, I cloned and ran this project locally and noticed that it is not up to date with the demo you have hosted. Can you please push the latest code?
Thanks

**Comment by antkaynak** [comment]
There are blank lines in the application.properties files in both resource server and authorization server. You must fill those lines with your own existing database credentials and your own email hosting service credentials. The hosted site is the same with the code base I pushed. If you enconder any more problems please let me know.

**Comment by antkaynak** [comment]
To run the application fill the lines in resource server and authorization server application.properties as well as frontend application service urls.
